apiVersion: getambassador.io/v2
kind: Module
name: ambassador
config:
  diagnostics:
    enabled: true
  use_ambassador_namespace: false
  gzip:
    enabled: true
  cors:
    origins: "*"
    methods: "*"
    headers: "*"
    expose_headers: "*"